### ISSUE TITLE
-m<arch> options should be mapped to /arch

### ISSUE THREAD

**Issue by Artoria2e5** [swig/cccl#1]
According to MSDN,

> # /G (Optimize for Processor) Options
> 
> **/G** is available in all editions of Visual C++, _but the compiler can perform more optimizations when /G is used with one of the /O compiler options._

It seems to show that `/G` is more like `-mtune`.

**Comment by wsfulton** [comment]
The /G options for processor (/G1 and /G2) seem to have been dropped, they aren't listed for VS2012 and later at https://msdn.microsoft.com/en-us/library/fwkeyyhe(v=vs.110).aspx. You probably got the MSDN quote from this page: https://msdn.microsoft.com/en-us/library/h66s5s0e(v=vs.100).aspx which also does not list versions > VS2010. The /G options that are currently mapped by cccl (/G3 /G4 /G5 /G6) also seem to have been dropped by Visual C++ as they aren't documented. 

I'm inclined to consider adding in any obvious mappings that are needed and ignore all other -m options. This will keep to the stated goal of keeping cccl simple and lightweight and any complex tuning of flags can of course be done by the user of cccl.

**Comment by wsfulton** [comment]
@Artoria2e5 if you have a pull request to implement this please submit it. Otherwise, let's close this issue.
