### ISSUE TITLE
README: replace / add to deprecated AM_PROG_LIBTOOL and AC_LIBTOOL_WIN32_DLL 

### ISSUE THREAD

**Issue by GitMensch** [swig/cccl#12]
Not sure if we should keep the old deprecated options at all - or just go with the "newer" one:

As seen in https://www.gnu.org/software/libtool/manual/html_node/LT_005fINIT.html

instead of

````
AC_LIBTOOL_WIN32_DLL
AM_PROG_LIBTOOL
```

the "new" way (since years) should likely be the one (primarily) documented:

```
LT_INIT [win32-dll]
```

**Comment by wsfulton** [comment]
Good observation, fixing...
