### ISSUE TITLE
[request] Add 1.3 release tag

### ISSUE THREAD

**Issue by danimtb** [swig/cccl#18]
Hi!

I have noticed that this library is making its way to [ConanCenter](https://conan.io/center/) package repository via this PR: https://github.com/conan-io/conan-center-index/pull/14115

We would like to add there the latest version 1.3 of this library, but there is no current tag for this version right now. Although we can make our way around it, it would be nice to have a tag for it so we can pinpoint that release source bundle.

Would it be possible to have a tag for that 1.3 release? Thank you 😄

**Comment by wsfulton** [comment]
v1.3 is work in progress and hasn't been released. I don't mind releasing it though, so will do that shortly.

**Comment by danimtb** [comment]
That was awesome @wsfulton! Thanks a lot 😄 Now https://github.com/conan-io/conan-center-index/pull/14115 is ready and will be merged shortly. Soon it could be installed via Conan 😍
